# Important:
# To sync: <leader> r 
# To install packages: <leader> I
#


# Refresh the configuration
unbind r
bind r source-file ~/.tmux.conf

# Set a new leader key (similar idea to leader key and neovim) 
set -g prefix C-s

# Set vim motions for pane selection
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# List of plugins
# Basic plugin manager
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'dracula/tmux'


# Set up status bar
# Powerline design
set -g @dracula-show-flags true
set -g @dracula-show-powerline false 
set -g @dracula-transparent-powerline-bg true
# Powerline data
set -g @dracula-show-fahrenheit false
font_dark="#1b1b2a"
font_light="#f8f8f2"
virgin_cpu='#FCEE0C'
set -g @dracula-cpu-usage-colors "virgin_cpu font_dark"
set -g @dracula-cpu-usage-label ""
virgin_gpu='#03daf3'
set -g @dracula-gpu-usage-label "󰢮"
set -g @dracula-gpu-usage-colors "virgin_gpu font_dark"
virgin_ram='#1b1b2a'
set -g @dracula-ram-usage-colors "virgin_ram font_light"
set -g @dracula-ram-usage-label ""
# This was a blank space 
set -g @dracula-plugins "cpu-usage gpu-usage ram-usage"
set -g @dracula-show-left-icon session

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
