# Important:
# To sync: <leader> r 
# To install packages: <leader> I
#

# Refresh the configuration
unbind r
bind r source-file ~/.tmux.conf

# Set a new leader key (similar idea to leader key and neovim) 
set -g prefix C-s

# Terminal/neovim colorscheme
set-option -a terminal-features 'alacritty:RGB'
set-option -a terminal-overrides ",alacritty:TC"

# Set vim motions for pane selection
setw -g mode-keys vi
set -g mouse on
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# List of plugins
# Basic plugin manager
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'o0th/tmux-nova'
set -g @plugin 'thewtex/tmux-mem-cpu-load'

# My colors
font_dark="#1b1b2a"
font_light="#f8f8f2"
bar_color="#131b24"
virgin_cpu='#FCEE0C'

# Status bar config
set -g status-position top
set -g status-bg "#131b24" 
#
set -g @nova-nerdfonts true
set -g @nova-nerdfonts-left ''
set -g @nova-nerdfonts-right ''
# Mode 
set -g @nova-segment-mode "#{?client_prefix, ||! COMMAND, | NORMAL}"
set -g @nova-segment-mode-colors "#8fe87b #1b1b2a"
# User
set -g @nova-segment-whoami "#(whoami)@#h"
set -g @nova-segment-whoami-colors "#c272f7 #1b1b2a"
# Pane
set -g @nova-pane "#I#{?pane_in_mode,  #{pane_mode},}  #W"
set -g @nova-rows 0
set -g @nova-segments-0-left "mode"
set -g @nova-segments-0-right "whoami"

# Still cooking
set -g status-interval 2
set -g status-right '#[fg=green]#(~/.tmux/plugins/tpm/tmux-mem-cpu-load/tmux-mem-cpu-load --colors --powerline-right --interval 2)#[default]'
set -g status-right-length 60





# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
